feat: Add more evaluation samples. Add histograms

diff --git a/apps/second-brain-online/Makefile b/apps/second-brain-online/Makefile
--- a/apps/second-brain-online/Makefile
+++ b/apps/second-brain-online/Makefile
@@ -17,6 +17,14 @@ RETRIEVER_CONFIG ?= configs/compute_rag_vector_index_openai_parent.yaml
 help:
 	@grep -E '^[a-zA-Z0-9 -]+:.*#'  Makefile | sort | while read -r l; do printf "\033[1;32m$$(echo $$l | cut -f 1 -d':')\033[00m:$$(echo $$l | cut -f 2- -d'#')\n"; done
 
+check-config:
+	@if [ ! -f "$(RETRIEVER_CONFIG)" ]; then \
+		echo "Error: Retriever config file '$(RETRIEVER_CONFIG)' does not exist"; \
+		exit 1; \
+	else \
+		echo "Found retriever config file at '$(RETRIEVER_CONFIG)'"; \
+	fi
+
 # --- Infrastructure --- 
 
 local-docker-infrastructure-up:
@@ -32,13 +40,13 @@ local-infrastructure-stop: local-docker-infrastructure-stop
 
 # --- Run ---
 
-run_agent_app:
+run_agent_app: check-config
 	uv run python -m tools.app --retriever-config-path=$(RETRIEVER_CONFIG) --ui
 
-run_agent_query:
-	uv run python -m tools.app --retriever-config-path=$(RETRIEVER_CONFIG) --query "What is the feature/training/inference (FTI) pipelines architecture?"
+run_agent_query: check-config
+	uv run python -m tools.app --retriever-config-path=$(RETRIEVER_CONFIG) --query "What's the difference between vector databases and vector indices?"
 
-evaluate_agent:
+evaluate_agent: check-config
 	uv run python -m tools.evaluate_app --retriever-config-path=$(RETRIEVER_CONFIG)
 
 
